CREATE TABLE [dbo].[Posts]
(
  [PostId] UNIQUEIDENTIFIER NOT NULL,
  [PostTitle] NVARCHAR(MAX) NOT NULL,
  [PostContent] NVARCHAR(MAX) NOT NULL,
  [PostCreatedDate] DATETIME NOT NULL,
  [PostOwnerUserName] NVARCHAR(MAX) NOT NULL,
  [Ratings] INT NULL DEFAULT 0,
  [IsNSFW] BIT NULL,
  [GenreTag] NVARCHAR(MAX) NULL,
  [PostModifedDate] DATETIME NOT NULL DEFAULT GETUTCDATE(),
  [IsActive] BIT NOT NULL DEFAULT 1,
)
