CREATE TABLE [dbo].[PostRatings]
(
  [PostRatingId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [PostId] UNIQUEIDENTIFIER NOT NULL,
  [UserName] NVARCHAR(256) NOT NULL,
  [RatedOn] DATETIME NOT NULL DEFAULT GETDATE(),
  [PreviousRatingValue] INT NOT NULL DEFAULT 0,
  [IsActive] BIT NOT NULL DEFAULT 1
)