CREATE TABLE [dbo].[Posts]
(
  [PostId] UNIQUEIDENTIFIER NOT NULL,
  [PostTitle] NVARCHAR(MAX) NOT NULL,
  [PostContent] NVARCHAR(MAX) NOT NULL,
  [PostCreatedDate] DATETIME NOT NULL,
  [PostOwnerUserName] NVARCHAR(MAX) NOT NULL,
  [IsActive] BIT DEFAULT 1
)
