CREATE TABLE [dbo].[PostRatings]
(
  [PostRatingId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [PostId] UNIQUEIDENTIFIER NOT NULL,
  [UserName] NVARCHAR(256) NOT NULL,
  [RatedOn] DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT FK_PostRatings_Posts FOREIGN KEY (PostId) REFERENCES Posts(PostId)
)