export const TOGGLE_ERROR_TOASTER = "TOGGLE_ERROR_TOASTER";
export const TOGGLE_SUCCESS_TOASTER = "TOGGLE_SUCCESS_TOASTER";
export const TOGGLE_SIDE_BAR_STATUS = "TOGGLE_SIDE_BAR_STATUS";
export const SAVE_BUG_REPORT_DATA = "SAVE_BUG_REPORT_DATA";
export const TOGGLE_BUG_REPORT_SPINNER = "TOGGLE_BUG_REPORT_SPINNER";
export const TOGGLE_BUG_REPORT_DRAWER = "TOGGLE_BUG_REPORT_DRAWER";
export const GET_LOOKUP_MASTER_DATA = "GET_LOOKUP_MASTER_DATA";
