CREATE TABLE [dbo].[PostRatings]
(
  [PostRatingId] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
  [PostId] UNIQUEIDENTIFIER NOT NULL,
  [UserName] NVARCHAR(256) NOT NULL,
  [RatedOn] DATETIME NOT NULL DEFAULT GETDATE(),
  [RatingValue] INT NOT NULL DEFAULT 0,
  [IsActive] BIT NOT NULL DEFAULT 1
)