global using InternetBulletin.Business.Services;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.Logging;
global using Moq;
global using System.Threading.Tasks;
global using InternetBulletin.Data.Contracts;
global using InternetBulletin.Shared.DTOs.Posts;
global using Xunit;
global using InternetBulletin.Shared.Helpers;
global using System.Net;
global using InternetBulletin.Shared.Constants;
global using InternetBulletin.Business.Contracts;
global using Microsoft.Extensions.Configuration;
global using static InternetBulletin.UnitTests.Helpers.TestsHelper;