### WEB
@baseUrl https://localhost:44315

GET {{baseUrl}}/InternetBulletinWeb/GetResourceUrl?resourceUrl=InternetBulletinApi/GetData?id=10
x-antiforgery-token-web: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiVXNlciIsIklzc3VlciI6IkludGVybmV0LUJ1bGxldGluLVdlYiJ9.1kR0l-Q5EUwmAykORxbMjGV9OTQ2UJKvDXMEQduW8o8