export const GET_APPLICATION_INFORMATION = "GET_APPLICATION_INFORMATION";
export const TOGGLE_ABOUT_US_SPINNER = "TOGGLE_ABOUT_US_SPINNER";
export const REWRITE_STORY_AI = "REWRITE_STORY_AI";
export const TOGGLE_REWRITE_LOADER = "TOGGLE_REWRITE_LOADER";
export const HANDLE_POST_AI_MODERATION = "HANDLE_POST_AI_MODERATION";
