export const GET_CONFIGURATION_VALUE = "GET_CONFIGURATION_VALUE";
export const TOGGLE_ERROR_TOASTER = "TOGGLE_ERROR_TOASTER";
export const TOGGLE_SUCCESS_TOASTER = "TOGGLE_SUCCESS_TOASTER";
export const TOGGLE_SIDE_BAR_STATUS = "TOGGLE_SIDE_BAR_STATUS";
export const GET_APPLICATION_INFORMATION = "GET_APPLICATION_INFORMATION";
export const TOGGLE_ABOUT_US_SPINNER = "TOGGLE_ABOUT_US_SPINNER";