// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.DeleteUserAsync(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.DeleteUserAsync(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.UpdateUserAsync(InternetBulletin.Data.Entities.User)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.UpdateUserAsync(InternetBulletin.Data.Entities.User)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.AddNewUserAsync(InternetBulletin.Shared.DTOs.NewUserDTO)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.AddNewUserAsync(InternetBulletin.Shared.DTOs.NewUserDTO)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.GetUserAsync(InternetBulletin.Shared.DTOs.UserLoginDTO)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.GetUserAsync(InternetBulletin.Shared.DTOs.UserLoginDTO)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.GetAllUsersAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.UsersController.GetAllUsersAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "Logging", Scope = "member", Target = "~M:InternetBulletin.API.Controllers.ConfigurationController.GetConfigurationValue(System.String)~Microsoft.AspNetCore.Mvc.IActionResult")]
